CREATE TABLE IF NOT EXISTS leads (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner VARCHAR(64) NOT NULL,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL,
 plan ENUM('free','paid') NOT NULL,
 status ENUM('free','pending','paid') NOT NULL,
 intent VARCHAR(64) NULL UNIQUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(owner)
);
