import React, { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useParams, useSearchParams } from 'react-router-dom';
import { api, getSession, Lead } from './api';
import './style.css';

function App() {
  return <BrowserRouter basename="/app"><div className="shell"><header><Link className="brand" to="/"><span className="brand-icon">↗</span> sellerboost<span className="brand-dot">.</span></Link><nav><a href="/legacy/">Explore legacy <span>↗</span></a><Link className="nav-cta" to="/signup">Get started <span>→</span></Link></nav></header><Routes><Route path="/" element={<Landing/>}/><Route path="/signup" element={<Signup/>}/><Route path="/checkout/:id" element={<Checkout/>}/><Route path="*" element={<section className="form-page"><h1>Page not found.</h1><Link to="/">Back to home →</Link></section>}/></Routes><footer><span className="brand small">sellerboost.</span><span>A small step for your business. A smarter way forward.</span><a href="/legacy/admin.php">Demo admin ↗</a></footer></div></BrowserRouter>;
}
function Landing() {
  return <main><section className="hero"><div><div className="eyebrow"><span className="status-dot"/> BUILT FOR INDEPENDENT SELLERS</div><h1>Start small.<br/>Sell <em>smarter.</em></h1><p className="intro">Your next chapter starts with a simple plan. Get practical tools to turn more visitors into customers.</p><Link className="button" to="/signup">Find your starting point <span>↗</span></Link><p className="micro">No subscription. No payment details to get started.</p></div><div className="toolkit"><div className="kit-top"><span>YOUR NEXT CHAPTER</span><span>01 / 03</span></div><div className="kit-art" aria-hidden="true"><div className="orbit"/><div className="growth-bars"><i/><i/><i/><i/></div><div className="arrow">↗</div></div><div className="kit-bottom"><h2>Less guesswork.<br/>More momentum.</h2><p>A clear path from your first<br/>visitor to your next sale.</p></div><div className="kit-tag">THE SELLER TOOLKIT ↗</div></div></section><section className="plans" id="plans"><div className="section-title"><div><span className="eyebrow">MAKE YOUR NEXT MOVE</span><h2>A little help. A big difference.</h2></div><p>Choose the toolkit that fits where you are.</p></div><div className="plan-grid"><article><div className="plan-label">01 <span>START WITH THE BASICS</span></div><h3>The first step</h3><p>Find your focus with a practical seller checklist.</p><div className="price">Free <small>always a good place to start</small></div><ul><li>A getting-started checklist</li><li>A simple plan for your next move</li></ul><Link className="button secondary" to="/signup?plan=free">Start for free <span>→</span></Link></article><article className="pro"><div className="plan-label">02 <span>BUILD YOUR MOMENTUM</span><b>PRO</b></div><h3>The growth toolkit</h3><p>Go further with a complete plan for your funnel.</p><div className="price">$29 <small>one-time · no subscription</small></div><ul><li>Everything in the free checklist</li><li>The complete seller growth toolkit</li></ul><Link className="button" to="/signup?plan=paid">Choose Pro <span>→</span></Link></article></div></section><aside className="lab-note"><span>↔</span><div><strong>One funnel. Two generations.</strong><p>This migration lab runs React and legacy PHP on the same data. All payments are simulated.</p></div><a href="/legacy/">Compare the legacy flow ↗</a></aside></main>;
}
function Signup() {
  const [params] = useSearchParams(); const [plan, setPlan] = useState(params.get('plan') === 'paid' ? 'paid' : 'free');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget);
    try { const row = await api<Lead>('/leads', 'POST', { name: data.get('name'), email: data.get('email'), plan }); window.location.assign(row.checkoutUrl!); }
    catch (ex) { setError(ex instanceof Error ? ex.message : 'Could not save your signup.'); setBusy(false); }
  }
  return <main className="form-page"><Link className="back" to="/">← Back to the toolkits</Link><span className="eyebrow">YOUR FIRST STEP</span><h1>Let’s get you<br/><em>moving.</em></h1><p>Pick your toolkit. We’ll save your spot.</p><form onSubmit={submit} className="form-card"><label>Your name<input name="name" required maxLength={100} autoComplete="name" placeholder="Alex Morgan"/></label><label>Email address<input name="email" required type="email" maxLength={254} autoComplete="email" placeholder="alex@example.com"/></label><fieldset><legend>Your toolkit</legend><label className={'choice '+(plan === 'free' ? 'selected' : '')}><input type="radio" name="plan" value="free" checked={plan === 'free'} onChange={() => setPlan('free')}/><span>The first step <small>Getting-started checklist</small></span><strong>Free</strong></label><label className={'choice '+(plan === 'paid' ? 'selected' : '')}><input type="radio" name="plan" value="paid" checked={plan === 'paid'} onChange={() => setPlan('paid')}/><span>The growth toolkit <small>Complete seller toolkit</small></span><strong>$29</strong></label></fieldset>{error && <p role="alert" className="error">{error}</p>}<button disabled={busy} className="button">{busy ? 'Saving your spot…' : 'Continue'} <span>→</span></button><p className="micro">Demo signup. No emails are sent. Checkout follows the migration flag.</p></form></main>;
}
function Checkout() {
  const { id } = useParams(); const [row, setRow] = useState<Lead>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); setError(''); Promise.all([getSession(), api<Lead>('/leads/'+id)]).then(([session, lead]) => { if (!active) return; if (!session.migrateCheckout) { window.location.replace('/legacy/payment.php?id='+lead.id); return; } setRow(lead); }).catch(ex => { if (active) setError(ex.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]);
  async function pay() { setBusy(true); setError(''); try { const intent = await api<{intent: string}>('/leads/'+id+'/intent', 'POST'); setRow(await api<Lead>('/leads/'+id+'/pay', 'POST', intent)); } catch (ex) { setError(ex instanceof Error ? ex.message : 'Please retry.'); } finally { setBusy(false); } }
  return <main className="form-page"><Link className="back" to="/">← Back to home</Link><span className="eyebrow">CHECKOUT STATUS</span>{loading ? <h1>Just a moment…</h1> : row ? <><h1>{row.status === 'pending' ? <>Your next<br/><em>chapter.</em></> : <>You’re all<br/><em>set.</em></>}</h1><div className="form-card"><span className="badge">{row.status === 'pending' ? 'AWAITING DEMO PAYMENT' : row.status === 'paid' ? 'PAYMENT COMPLETE' : 'FREE PLAN ACTIVE'}</span><h2>Thanks, {row.name}.</h2><p>{row.plan === 'paid' ? 'The growth toolkit' : 'The first step'} · {row.email}</p><div className="receipt"><span>{row.plan === 'paid' ? 'One-time total' : 'Your total'}</span><strong>{row.plan === 'paid' ? '$29.00 USD' : '$0'}</strong></div>{row.status === 'pending' ? <><p>This is a simulated checkout. No card details, no real charge.</p><button className="button" disabled={busy} onClick={pay}>{busy ? 'Processing…' : 'Simulate payment'} <span>→</span></button></> : <p>Your registration is saved in our shared database. This demo does not deliver a digital product.</p>}<p className="micro">Registration #{row.id} · Status: {row.status}</p></div></> : <h1>Unable to load<br/>your checkout.</h1>}{error && <p role="alert" className="error">{error}</p>}</main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
